- name: configure dispatch server
  hosts: dispatch
  become: yes
  tasks:
  - name: Install golang
    ansible.builtin.package:
      name: golang
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download backend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Build software
    ansible.builtin.command: go mod init dispatch; go get; go build

  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

 
  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes