- name: configure rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Setup mongoDB repo file
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Install rabbitmq db server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed
  
  - name: Start and enable rabbitmq
    ansible.builtin.systemd:
      name: rabbitmq-server
      state: started
      enabled: true

    
  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop1234
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present
